export const Colors = {
  primary: '#51644f',
  'primary-container': '#d3e8ce',
  'primary-fixed': '#d3e8ce',
  'primary-fixed-dim': '#c5dac0',
  'primary-dim': '#465843',
  'on-primary': '#eaffe4',
  'on-primary-container': '#445642',
  'on-primary-fixed': '#324431',
  'on-primary-fixed-variant': '#4e604b',
  'inverse-primary': '#e7fde1',

  secondary: '#6a5e46',
  'secondary-container': '#f2e0c3',
  'secondary-fixed': '#f2e0c3',
  'secondary-fixed-dim': '#e3d2b5',
  'secondary-dim': '#5d523b',
  'on-secondary': '#fff8f1',
  'on-secondary-container': '#5c503a',
  'on-secondary-fixed': '#493e29',
  'on-secondary-fixed-variant': '#665a43',

  tertiary: '#8f4f14',
  'tertiary-container': '#ffab69',
  'tertiary-fixed': '#ffab69',
  'tertiary-fixed-dim': '#ef9e5d',
  'tertiary-dim': '#804307',
  'on-tertiary': '#fff7f4',
  'on-tertiary-container': '#5d2e00',
  'on-tertiary-fixed': '#3e1d00',
  'on-tertiary-fixed-variant': '#6a3500',

  surface: '#fbf9f5',
  'surface-bright': '#fbf9f5',
  'surface-dim': '#dadad4',
  'surface-container': '#efeee9',
  'surface-container-low': '#f5f4ef',
  'surface-container-lowest': '#ffffff',
  'surface-container-high': '#e9e8e3',
  'surface-container-highest': '#e3e3dc',
  'surface-tint': '#51644f',
  'surface-variant': '#e3e3dc',

  background: '#fbf9f5',
  'on-background': '#31332f',
  'on-surface': '#31332f',
  'on-surface-variant': '#5e605b',
  'inverse-surface': '#0e0e0d',
  'inverse-on-surface': '#9e9d99',

  outline: '#7a7b76',
  'outline-variant': '#b2b2ad',

  error: '#a73b21',
  'error-container': '#fd795a',
  'error-dim': '#791903',
  'on-error': '#fff7f6',
  'on-error-container': '#6e1400',
} as const;

export type ColorToken = keyof typeof Colors;
